local colors = {
-- content here will not be touched
-- PATCH_OPEN
Normal = {fg = "#80D4FF", bg = "None"},
NormalFloat = {link = "Normal"},
Boolean = {fg = "#4DC3FF"},
Character = {fg = "#80FF80"},
ColorColumn = {fg = "None", bg = "#262626"},
Comment = {fg = "#BFBFBF"},
Conditional = {fg = "#D580FF"},
Constant = {fg = "#ABD7ED"},
CurSearch = {fg = "#000000", bg = "#E7EF8F"},
Cursor = {fg = "#000000", bg = "#E6E6E6"},
CursorIM = {link = "Cursor"},
TermCursor = {link = "Cursor"},
TermCursorNC = {link = "Cursor"},
lCursor = {link = "Cursor"},
CursorColumn = {bg = "#4D4D4D"},
CursorLine = {bg = "#4D4D4D"},
CursorLineNr = {fg = "#999999"},
Define = {fg = "#FFBF80"},
Delimiter = {fg = "#E6E6E6"},
DiagnosticError = {fg = "#FF8080", bg = "#290000"},
DiagnosticHint = {fg = "#D580FF", bg = "#1B0029"},
DiagnosticInfo = {fg = "#80D4FF", bg = "#001B29"},
DiagnosticOk = {fg = "#E7EF8F", bg = "None"},
DiagnosticUnderlineError = {fg = "#FF8080", bg = "#290000", undercurl = true},
DiagnosticUnderlineHint = {fg = "#D580FF", bg = "#1B0029", undercurl = true},
DiagnosticUnnecessary = {link = "DiagnosticUnderlineHint"},
DiagnosticUnderlineInfo = {fg = "#80D4FF", bg = "#001B29", undercurl = true},
DiagnosticUnderlineOk = {fg = "#E7EF8F", bg = "None", undercurl = true},
DiagnosticUnderlineWarn = {fg = "#E7EF8F", bg = "#212405", undercurl = true},
DiagnosticWarn = {fg = "#E7EF8F", bg = "#212405"},
DiffAdd = {fg = "#4DFF4D", bg = "#004200"},
DiffChange = {fg = "#E7EF8F", bg = "#3E430A"},
DiffDelete = {fg = "#FF8080", bg = "#4D0000"},
Directory = {fg = "#70CFFF"},
ErrorMsg = {fg = "#FF8080"},
Exception = {fg = "#FF8080"},
Float = {fg = "#ABD7ED"},
Folded = {fg = "#000000", bg = "#BFBFBF"},
Function = {fg = "#E7EF8F"},
IblScope = {fg = "#BFBFBF"},
Identifier = {fg = "#80D4FF"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#000000", bg = "#E7EF8F"},
Keyword = {fg = "#D580FF"},
Label = {fg = "#D580FF"},
LineNr = {fg = "#4D4D4D"},
Macro = {fg = "#FFBF80"},
MatchParen = {bg = "#999999"},
NonText = {fg = "#4D4D4D"},
Number = {fg = "#ABD7ED"},
Operator = {fg = "#ABD7ED"},
PmenuSel = {fg = "#000000", bg = "#E7EF8F"},
Repeat = {fg = "#D580FF"},
Special = {fg = "#4DC3FF", bold = true},
StatusLine = {bg = "None"},
StatusLineNC = {bg = "#262626"},
String = {fg = "#80FF80"},
Substitute = {fg = "#000000", bg = "#E7EF8F"},
Tabline = {},
TablineActive = {fg = "#E7EF8F", bold = true},
TablineEnd = {bg = "None"},
TablineFill = {},
TablineInactive = {bg = "None"},
TablineSel = {},
Todo = {fg = "#4DFF4D", bg = "#004200", bold = true},
["@text.todo"] = {link = "Todo"},
TreesitterContext = {bg = "None"},
TreesitterContextBottom = {bg = "None"},
TreesitterContextBottomLineNumber = {fg = "#737373", bg = "None"},
TreesitterContextLineNumber = {fg = "#4D4D4D"},
TreesitterContextSeparator = {fg = "#737373"},
Type = {fg = "#4DC3FF"},
["@type.builtin.rust"] = {link = "Type"},
Visual = {bg = "#737373"},
WinSeparator = {fg = "#E6E6E6"},
VertSplit = {link = "WinSeparator"},
manOptionDesc = {fg = "#80FF80"},
manSectionHeading = {fg = "#E6E6E6", bg = "#171717"},
["@comment.documentation.rust"] = {fg = "#FFA347"},
["@constant.macro"] = {fg = "#FFBF80"},
["@function.macro.rust"] = {fg = "#FFBF80"},
["@lsp.type.decorator.rust"] = {fg = "#FFBF80"},
["@lsp.type.selfKeyword.rust"] = {fg = "#FF8080", bold = true},
["@lsp.typemod.comment.documentation.rust"] = {fg = "#FFA347"},
["@lsp.typemod.decorator.attribute.rust"] = {fg = "#FFBF80"},
["@lsp.typemod.decorator.defaultLibrary.rust"] = {fg = "#FFBF80"},
["@lsp.typemod.decorator.library.rust"] = {fg = "#FFBF80"},
["@lsp.typemod.selfKeyword.declaration.rust"] = {fg = "#FF8080", bold = true},
["@lsp.typemod.selfKeyword.mutable.rust"] = {underline = true},
["@lsp.typemod.selfKeyword.reference.rust"] = {fg = "#FF8080", bold = true},
["@lsp.typemod.variable.mutable.rust"] = {underline = true},
["@module"] = {fg = "#FFBF80"},
["@namespace"] = {fg = "#FFBF80"},
["@variable.builtin.rust"] = {fg = "#FF8080", bold = true},
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='my_theme'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
